---
title: "FAQ"
weight: 23
---


#### Why can't I see my graph?

One common reason why your `ggplot2` graph may not be displaying is because you may have not typed the name of your graph and run it.

#### R cannot find the variable I would like to plot.

There are a two common reasons why R might not be able to find your variable. 
Check that you have spelt the name exactly as it appears in the dataset (remember that you can use the codebook to check variable names and descriptions to do this)

Another possibility is that you may have not used the `$` to explicitly state which variable you would like R to find.

#### How do I save my plot?

Once you plot your graph in the bottom right panel of R studio, you can use the `ggsave()` function to save your most recent plot. Your code should look something like:

`ggsave("the_name_of_your_plot_here")`


#### I can't find the plot that I saved.

Whenever you use the `ggsave()` function, your plot will be saved in your working directory. If you are not sure what your working directory is, use the `getwd()` function which will show you were in your pc plot was saved to.


#### I keep receiving an error when I try to use `ggplot2`. 

Check if you have called `ggplot2` from your library using the function `library(ggplot2)`. 

* If you are doing any extended work involving data analysis, plotting and data cleaning you might find it easier to call the entire `tidyverse` from your library using the function `library(tidyverse)`

#### I keep receiving and error when trying to use ggplot. 

Check if you have called ggplot from your library using the function `library(ggplot2)`.