---
title: Construct and plot your interaction term 
weight: 34
---

```{r data, include=FALSE}
library(sjlabelled)
EVS <- read_stata("ZA7500_v2-0-0.dta")
library(dplyr)
select(EVS, v102, v185, v189,v190, v191, v192, v193, v225,v226,v243_edulvlb,country,v175_cs,v275c_N1)
EVS.Germany<-EVS %>% filter(country == 276) 
table(EVS.Germany$country)
EVS.Germany[EVS.Germany <=-1] <- NA
EVS.Germany[EVS.Germany <=-2] <- NA
EVS.Germany<-EVS.Germany %>% mutate(immi.jobs=(max(v185,na.rm=TRUE)-(v185)))
EVS.Germany<-EVS.Germany %>% mutate(born.country=(max(v189,na.rm=TRUE)-(v189)))
EVS.Germany<-EVS.Germany %>% mutate(respect.inst=(max(v190,na.rm=TRUE)-(v190)))
EVS.Germany<-EVS.Germany %>% mutate(country.ancestry=(max(v191,na.rm=TRUE)-(v191)))
EVS.Germany<-EVS.Germany %>% mutate(speak.lang=(max(v192,na.rm=TRUE)-(v192)))
EVS.Germany<-EVS.Germany %>% mutate(share.cultr=(max(v193,na.rm=TRUE)-(v193)))
EVS.Germany<-EVS.Germany %>% rename(education=v243_edulvlb)
EVS.Germany<-EVS.Germany %>% rename(left_right=v102)
EVS.Germany<-EVS.Germany %>% rename(region=v275c_N1)
table(EVS.Germany$region)
EVS.Germany$east_west <- NA
EVS.Germany$east_west[EVS.Germany$region==27604] <- 1
EVS.Germany$east_west[EVS.Germany$region==27608] <- 1
EVS.Germany$east_west[EVS.Germany$region==27613] <- 1 
EVS.Germany$east_west[EVS.Germany$region==27614] <- 1
EVS.Germany$east_west[EVS.Germany$region==27616] <- 1 
EVS.Germany$east_west[EVS.Germany$region==27603] <- 0
EVS.Germany$east_west[EVS.Germany$region==27607] <- 0
EVS.Germany$east_west[EVS.Germany$region==27609] <- 0
EVS.Germany$east_west[EVS.Germany$region==27610] <- 0
EVS.Germany$east_west[EVS.Germany$region==27611] <- 0
EVS.Germany$east_west[EVS.Germany$region==27612] <- 0
EVS.Germany$east_west[EVS.Germany$region==27615] <- 0
table(EVS.Germany$east_west)
```    

The $:$ designates the interaction between two variables. The operator $*$ designates the interaction between the two variables, plus the main effects. In our model we included an interaction term between two variables `born.country` and `east_west`. 


```{r regression}
model.1<-lm(immi.jobs~ born.country*east_west+country.ancestry+share.cultr+left_right+education,data=EVS.Germany)
summary(model.1)
```

It is important to plot the outcome of the interaction term. To do so you may use the `interplot()` package. 

```{r interplot, message=FALSE, warning=FALSE}
library(interplot)
interaction<-interplot(m = model.1, var1 = "born.country", var2 =  "east_west") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))+ # This will center the title of your plot
  geom_hline(yintercept = 0, linetype = "dashed") +
  ggtitle("Marginal Effects: East versus West")

interaction
```

